behaviors:
  MNG_Manager:
    trainer_type: ppo
    init_path: results/MNG_MS2-20260921-r005/MNG_Manager/MNG_Manager-99968.pt
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.00005
      beta: 0.003
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 300000
    time_horizon: 128
    summary_freq: 1000
    checkpoint_interval: 50000
    keep_checkpoints: 21
    threaded: false
    self_play:
      save_steps: 25000
      team_change: 100000
      swap_steps: 25000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
